name: test workflow
on: workflow_dispatch

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "."
          # The directory to scan
          arguments: --allow-missing-href
          # The arguments to pass to HTMLProofer

