name: test workflow
on: workflow_dispatch

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          blacklist: invalid

